### ISSUE TITLE
Все страницы > Левое меню > Блог навигации

### ISSUE THREAD

**Issue by paulcodiny** [BorisTheB1ad3/project1#3]
- Все ссылки пускай ведут на страницу блога, страница Work на страницу продукта
- Ссылки имеют наведенное и активное состояние. На страницы продукта активна ссылка Work, на странице блога активна ссылка блог

**Comment by BorisTheB1ad3** [comment]
Коммит: 17b0871f78dcb5d8809c9a32c2c7cdb0a1b367af
